### ISSUE TITLE
Old react version dependencies

### ISSUE THREAD

**Issue by xennialex** [ericbiewener/react-global-events#1]
Hi!

Could you maybe update the dependencies in the package?

Currently it looks like this:
`  "peerDependencies": {
    "react": "^0.14 || ^15.0.0-rc || ^15.0"
  },`

The current version is React 17 so npm will show an error on `npm update`

**Comment by ericbiewener** [comment]
This is verrrrrrry unmaintained. I'd recommend just forking this repo and publishing your own package (or just copy the source code into your project!)
